In [3]:
import os
print('sales1.excel' in os.listdir())

False

In [4]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [7]:
excel_file = pd.ExcelFile('sales1.xlsx')
excel_file.sheet_names

['Customer', 'Orders']

In [8]:
import os
print(os.listdir())

['%userprofile%', '.ipynb_checkpoints', '0409', '1033', '69fe178f-26e7-43a9-aa7d-2b616b672dde_eventlogservice.dll', '6bea57fb-8dfb-4177-9ae8-42e8b3529933_RuntimeDeviceInstall.dll', '@AdvancedKeySettingsNotification.png', '@AppHelpToast.png', '@AudioToastIcon.png', '@BackgroundAccessToastIcon.png', '@bitlockertoastimage.png', '@edptoastimage.png', '@EnrollmentToastIcon.png', '@language_notification_icon.png', '@optionalfeatures.png', '@StorageSenseToastIcon.png', '@VpnToastIcon.png', '@windows-hello-V4.1.gif', '@WindowsHelloFaceToastIcon.png', '@WindowsUpdateToastIcon.contrast-black.png', '@WindowsUpdateToastIcon.contrast-white.png', '@WindowsUpdateToastIcon.png', '@WirelessDisplayToast.png', '@WLOGO_48x48.png', 'aadauthhelper.dll', 'aadcloudap.dll', 'aadjcsp.dll', 'aadtb.dll', 'aadWamExtension.dll', 'AarSvc.dll', 'AboutSettingsHandlers.dll', 'AboveLockAppHost.dll', 'accelerometerdll.DLL', 'accessibilitycpl.dll', 'accountaccessor.dll', 'AccountsRt.dll', 'AcGenral.dll', 'AcLayers.dll', 'acledit.dll', 'aclui.dll', 'acmigration.dll', 'ACPBackgroundManagerPolicy.dll', 'acppage.dll', 'acproxy.dll', 'AcSpecfc.dll', 'ActionCenter.dll', 'ActionCenterCPL.dll', 'ActionQueue.dll', 'ActivationClient.dll', 'ActivationManager.dll', 'activeds.dll', 'activeds.tlb', 'ActiveHours.png', 'ActiveSyncCsp.dll', 'ActiveSyncProvider.dll', 'actxprxy.dll', 'AcWinRT.dll', 'AcXtrnal.dll', 'adal.dll', 'AdaptiveCards.dll', 'AddressParser.dll', 'adhapi.dll', 'adhsvc.dll', 'AdmTmpl.dll', 'adprovider.dll', 'adrclient.dll', 'adsldp.dll', 'adsldpc.dll', 'adsmsext.dll', 'adsnt.dll', 'adtschema.dll', 'AdvancedEmojiDS.dll', 'AdvancedInstallers', 'advapi32.dll', 'advapi32res.dll', 'advpack.dll', 'aeevts.dll', 'aeinv.dll', 'aemarebackup.dll', 'aepic.dll', 'agentactivationruntime.dll', 'agentactivationruntimestarter.exe', 'agentactivationruntimewindows.dll', 'AgentService.exe', 'AggregatorHost.exe', 'aitstatic.exe', 'AJRouter.dll', 'alg.exe', 'altspace.dll', 'am-et', 'amcompat.tlb', 'amde31a.dat', 'amdgfxinfo64.dll', 'amdhdl64.dll', 'amdicdxx.dat', 'amdmiracast.dll', 'amdmmcl6.dll', 'amdocl12cl64.dll', 'amdocl64.dll', 'amdocl_as64.exe', 'amdocl_ld64.exe', 'amdpcom64.dll', 'amdxc64.dll', 'amsi.dll', 'amsiproxy.dll', 'amstream.dll', 'Analog.Shell.Broker.dll', 'AnalogCommonProxyStub.dll', 'apds.dll', 'APHostClient.dll', 'APHostRes.dll', 'APHostService.dll', 'apisampling.dll', 'ApiSetHost.AppExecutionAlias.dll', 'apisetschema.dll', 'APMon.dll', 'APMonUI.dll', 'AppContracts.dll', 'AppExtension.dll', 'apphelp.dll', 'Apphlpdm.dll', 'AppHostRegistrationVerifier.exe', 'appidapi.dll', 'appidcertstorecheck.exe', 'appidpolicyconverter.exe', 'AppIdPolicyEngineApi.dll', 'appidsvc.dll', 'appidtel.exe', 'appinfo.dll', 'appinfoext.dll', 'AppInstallerPrompt.Desktop.dll', 'ApplicationControlCSP.dll', 'ApplicationFrame.dll', 'ApplicationFrameHost.exe', 'AppListBackupLauncher.dll', 'AppLocker', 'AppLockerCSP.dll', 'ApplySettingsTemplateCatalog.exe', 'ApplyTrustOffline.exe', 'AppManagementConfiguration.dll', 'appmgmts.dll', 'appmgr.dll', 'AppMon.dll', 'AppointmentActivation.dll', 'AppointmentApis.dll', 'appraiser', 'appraiser.dll', 'AppReadiness.dll', 'apprepapi.dll', 'AppResolver.dll', 'ApproveChildRequest.exe', 'appsruprov.dll', 'AppV', 'AppVCatalog.dll', 'AppVClient.exe', 'AppvClientEventLog.dll', 'AppVClientPS.dll', 'AppVDllSurrogate.exe', 'AppVEntStreamingManager.dll', 'AppVEntSubsystemController.dll', 'AppVEntSubsystems64.dll', 'AppVEntVirtualization.dll', 'appvetwclientres.dll', 'appvetwsharedperformance.dll', 'appvetwstreamingux.dll', 'AppVFileSystemMetadata.dll', 'AppVIntegration.dll', 'AppVManifest.dll', 'AppVNice.exe', 'AppVOrchestration.dll', 'AppVPolicy.dll', 'AppVPublishing.dll', 'AppVReporting.dll', 'AppVScripting.dll', 'AppVSentinel.dll', 'AppVShNotify.exe', 'AppVStreamingUX.dll', 'AppVStreamMap.dll', 'AppVTerminator.dll', 'appwiz.cpl', 'AppxAllUserStore.dll', 'AppXApplicabilityBlob.dll', 'AppxApplicabilityEngine.dll', 'AppXDeploymentClient.dll', 'AppXDeploymentExtensions.desktop.dll', 'AppXDeploymentExtensions.onecore.dll', 'AppXDeploymentServer.dll', 'AppxPackaging.dll', 'AppxProvisioning.xml', 'AppxSip.dll', 'AppxStreamingDataSourcePS.dll', 'AppxSysprep.dll', 'ar-SA', 'archiveint.dll', 'ARP.EXE', 'asferror.dll', 'aspnet_counters.dll', 'AssignedAccessCsp.dll', 'AssignedAccessGuard.exe', 'AssignedAccessManager.dll', 'assignedaccessmanagersvc.dll', 'assignedaccessproviderevents.dll', 'AssignedAccessRuntime.dll', 'AssignedAccessShellProxy.dll', 'asycfilt.dll', 'at.exe', 'AtBroker.exe', 'atiadlxx.dll', 'atiapfxx.blb', 'atiapfxx.exe', 'aticalcl64.dll', 'aticaldd64.dll', 'aticalrt64.dll', 'aticfx64.dll', 'atidemgy.dll', 'atidxx64.dll', 'atieah64.exe', 'atieclxx.exe', 'atiesrxx.exe', 'atig6pxx.dll', 'atig6txx.dll', 'atiglpxx.dll', 'atiicdxx.dat', 'atimpc64.dll', 'atimuixx.dll', 'atio6axx.dll', 'ATIODCLI.exe', 'ATIODE.exe', 'atitmm64.dll', 'atiu9p64.dll', 'atiumd64.dll', 'atiumd6a.cap', 'atiumd6a.dll', 'atiuxp64.dll', 'ativce02.dat', 'ativce03.dat', 'ativvaxy_cik.dat', 'ativvaxy_cik_nd.dat', 'ativvaxy_cz_nd.dat', 'ativvaxy_FJ.dat', 'ativvaxy_FJ_nd.dat', 'ativvaxy_vi.dat', 'ativvaxy_vi_nd.dat', 'ativvsva.dat', 'ativvsvl.dat', 'atl.dll', 'atlthunk.dll', 'atmlib.dll', 'attrib.exe', 'audiodg.exe', 'AudioEndpointBuilder.dll', 'AudioEng.dll', 'AudioHandlers.dll', 'AUDIOKSE.dll', 'audioresourceregistrar.dll', 'AudioSes.dll', 'audiosrv.dll', 'AudioSrvPolicyManager.dll', 'auditcse.dll', 'AuditNativeSnapIn.dll', 'auditpol.exe', 'auditpolcore.dll', 'AuditPolicyGPInterop.dll', 'auditpolmsg.dll', 'AuthBroker.dll', 'AuthBrokerUI.dll', 'authentication.dll', 'AuthExt.dll', 'authfwcfg.dll', 'AuthFWGP.dll', 'AuthFWSnapin.dll', 'AuthFWWizFwk.dll', 'AuthHost.exe', 'AuthHostProxy.dll', 'authui.dll', 'authz.dll', 'autochk.exe', 'autoconv.exe', 'autofmt.exe', 'AutomaticAppSignInPolicy.dll', 'autopilot.dll', 'autopilotdiag.dll', 'autoplay.dll', 'autotimesvc.dll', 'AverageRoom.bin', 'avicap32.dll', 'avifil32.dll', 'avrt.dll', 'AxInstSv.dll', 'AxInstUI.exe', 'azman.msc', 'azroles.dll', 'azroleui.dll', 'AzSqlExt.dll', 'AzureCheck-events.dll', 'AzureSettingSyncProvider.dll', 'baaupdate.exe', 'BackgroundMediaPolicy.dll', 'backgroundTaskHost.exe', 'BackgroundTransferHost.exe', 'BamSettingsClient.dll', 'BarcodeProvisioningPlugin.dll', 'basecsp.dll', 'basesrv.dll', 'batmeter.dll', 'bcastdvr.proxy.dll', 'BcastDVRBroker.dll', 'BcastDVRClient.dll', 'BcastDVRCommon.dll', 'bcastdvruserservice.dll', 'bcd.dll', 'bcdboot.exe', 'bcdedit.exe', 'bcdprov.dll', 'bcdsrv.dll', 'BCP47Langs.dll', 'BCP47mrm.dll', 'bcrypt.dll', 'bcryptprimitives.dll', 'bdaplgin.ax', 'bdechangepin.exe', 'BdeHdCfg.exe', 'BdeHdCfgLib.dll', 'bderepair.dll', 'bdesvc.dll', 'BdeSysprep.dll', 'bdeui.dll', 'BdeUISrv.exe', 'bdeunlock.exe', 'bdmjpeg64.dll', 'bdmpega64.acm', 'bdmpegv64.dll', 'BFE.DLL', 'bg-BG', 'bi.dll', 'bidispl.dll', 'bindfltapi.dll', 'BingASDS.dll', 'BingFilterDS.dll', 'BingMaps.dll', 'BingOnlineServices.dll', 'BioCredProv.dll', 'BioIso.exe', 'bisrv.dll', 'BitLockerCsp.dll', 'BitLockerDeviceEncryption.exe', 'BitLockerWizard.exe', 'BitLockerWizardElev.exe', 'bitsadmin.exe', 'bitsigd.dll', 'bitsperf.dll', 'BitsProxy.dll', 'biwinrt.dll', 'BlbEvents.dll', 'blbres.dll', 'blb_ps.dll', 'BluetoothApis.dll', 'BluetoothDesktopHandlers.dll', 'BluetoothPairingSystemToastIcon.contrast-black.png', 'BluetoothPairingSystemToastIcon.contrast-high.png', 'BluetoothPairingSystemToastIcon.contrast-white.png', 'BluetoothPairingSystemToastIcon.png', 'BluetoothSystemToastIcon.contrast-white.png', 'BluetoothSystemToastIcon.png', 'bnmanager.dll', 'Boot', 'boot.sdi', 'bootcfg.exe', 'bootim.exe', 'BootMenuUX.dll', 'bootsect.exe', 'bootstr.dll', 'bootux.dll', 'BOOTVID.DLL', 'bopomofo.uce', 'bridgeres.dll', 'bridgeunattend.exe', 'BrokerLib.dll', 'browcli.dll', 'browserbroker.dll', 'browserexport.exe', 'BrowserSettingSync.dll', 'browser_broker.exe', 'browseui.dll', 'BTAGService.dll', 'BthAvctpSvc.dll', 'BthAvrcp.dll', 'BthAvrcpAppSvc.dll', 'bthci.dll', 'BthMtpContextHandler.dll', 'bthpanapi.dll', 'BthpanContextHandler.dll', 'Bthprops', 'bthprops.cpl', 'BthRadioMedia.dll', 'bthserv.dll', 'BthTelemetry.dll', 'bthudtask.exe', 'btpanui.dll', 'Bubbles.scr', 'BWContextHandler.dll', 'ByteCodeGenerator.exe', 'cabapi.dll', 'cabinet.dll', 'cabview.dll', 'cacls.exe', 'calc.exe', 'calibration.bin', 'CallButtons.dll', 'CallButtons.ProxyStub.dll', 'CallHistoryClient.dll', 'CameraCaptureUI.dll', 'CameraSettingsUIHost.exe', 'CapabilityAccessHandlers.dll', 'CapabilityAccessManager.dll', 'CapabilityAccessManagerClient.dll', 'capauthz.dll', 'capiprovider.dll', 'capisp.dll', 'CaptureService.dll', 'CastingShellExt.dll', 'CastLaunch.dll', 'CastSrv.exe', 'CatRoot', 'catroot2', 'catsrv.dll', 'catsrvps.dll', 'catsrvut.dll', 'CBDHSvc.dll', 'cca.dll', 'cdd.dll', 'cdosys.dll', 'cdp.dll', 'cdprt.dll', 'cdpsvc.dll', 'cdpusersvc.dll', 'CellularAPI.dll', 'cellulardatacapabilityhandler.dll', 'cemapi.dll', 'cero.rs', 'certca.dll', 'certcli.dll', 'certCredProvider.dll', 'certenc.dll', 'CertEnroll.dll', 'CertEnrollCtrl.exe', 'CertEnrollUI.dll', 'certlm.msc', 'certmgr.dll', 'certmgr.msc', 'CertPKICmdlet.dll', 'CertPolEng.dll', 'certprop.dll', 'certreq.exe', 'certutil.exe', 'cewmdm.dll', 'cfgbkend.dll', 'cfgmgr32.dll', 'CfgSPCellular.dll', 'CfgSPPolicy.dll', 'cflapi.dll', 'cfmifs.dll', 'cfmifsproxy.dll', 'Chakra.dll', 'Chakradiag.dll', 'Chakrathunk.dll', 'change.exe', 'changepk.exe', 'charmap.exe', 'chartv.dll', 'ChatApis.dll', 'chcp.com', 'CheckNetIsolation.exe', 'chglogon.exe', 'chgport.exe', 'chgusr.exe', 'chkdsk.exe', 'chkntfs.exe', 'chkwudrv.dll', 'choice.exe', 'ChsStrokeDS.dll', 'chs_singlechar_pinyin.dat', 'ChtAdvancedDS.dll', 'ChtBopomofoDS.dll', 'ChtCangjieDS.dll', 'ChtHkStrokeDS.dll', 'ChtQuickDS.dll', 'ChxAPDS.dll', 'ChxDecoder.dll', 'ChxHAPDS.dll', 'chxinputrouter.dll', 'chxranker.dll', 'CHxReadingStringIME.dll', 'ci.dll', 'cic.dll', 'CIDiag.exe', 'cimfs.dll', 'cipher.exe', 'CIRCoInst.dll', 'CIWmi.dll', 'clb.dll', 'clbcatq.dll', 'cldapi.dll', 'cleanmgr.exe', 'CleanPCCSP.dll', 'clfsw32.dll', 'cliconfg.dll', 'cliconfg.exe', 'cliconfg.rll', 'clinfo.exe', 'clip.exe', 'ClipboardServer.dll', 'Clipc.dll', 'clipesu.exe', 'ClipESUConsumer.exe', 'ClipRenew.exe', 'ClipSVC.dll', 'ClipUp.exe', 'clipwinrt.dll', 'cloudAP.dll', 'CloudDomainJoinAUG.dll', 'CloudDomainJoinDataModelServer.dll', 'CloudExperienceHost.dll', 'CloudExperienceHostBroker.dll', 'CloudExperienceHostBroker.exe', 'CloudExperienceHostCommon.dll', 'CloudExperienceHostRedirection.dll', 'CloudExperienceHostUser.dll', 'cloudidsvc.dll', 'CloudIdWxhExtension.dll', 'CloudNotifications.exe', 'CloudRestoreLauncher.dll', 'clrhost.dll', 'clusapi.dll', 'cmcfg32.dll', 'cmd.exe', 'cmdext.dll', 'cmdial32.dll', 'cmdkey.exe', 'cmdl32.exe', 'cmgrcspps.dll', 'cmifw.dll', 'cmintegrator.dll', 'cmlua.dll', 'cmmon32.exe', 'cmpbk32.dll', 'cmstp.exe', 'cmstplua.dll', 'cmutil.dll', 'cngcredui.dll', 'cngprovider.dll', 'cnvfat.dll', 'cob-au.rs', 'CodeIntegrity', 'CodeIntegrityAggregator.dll', 'cofire.exe', 'cofiredm.dll', 'coinst_15.20.dll', 'colbact.dll', 'coloradapterclient.dll', 'COLORCNV.DLL', 'colorcpl.exe', 'colorui.dll', 'Com', 'combase.dll', 'comcat.dll', 'comctl32.dll', 'comdlg32.dll', 'comexp.msc', 'coml2.dll', 'comp.exe', 'compact.exe', 'compatrel', 'CompatTelRunner.exe', 'compmgmt.msc', 'CompMgmtLauncher.exe', 'ComposableShellProxyStub.dll', 'ComposerFramework.dll', 'CompPkgSrv.exe', 'CompPkgSup.dll', 'compstui.dll', 'computecore.dll', 'computelibeventlog.dll', 'computenetwork.dll', 'ComputerDefaults.exe', 'ComputerToastIcon.contrast-white.png', 'ComputerToastIcon.png', 'computestorage.dll', 'comrepl.dll', 'comres.dll', 'comsnap.dll', 'comsvcs.dll', 'comuid.dll', 'concrt140.dll', 'config', 'configmanager2.dll', 'Configuration', 'ConfigureExpandedStorage.dll', 'conhost.exe', 'ConhostV1.dll', 'connect.dll', 'ConnectedAccountState.dll', 'consent.exe', 'ConsentExperienceCommon.dll', 'ConsentUX.dll', 'ConsentUxClient.dll', 'console.dll', 'ConsoleLogon.dll', 'ConstraintIndex.Search.dll', 'consumeresumgr.dll', 'ContactActivation.dll', 'ContactApis.dll', 'ContactHarvesterDS.dll', 'container.dll', 'containerdevicemanagement.dll', 'ContainerSettingsProviders', 'ContentDeliveryManager.Utilities.dll', 'control.exe', 'convert.exe', 'convertvhd.exe', 'coreaudiopolicymanagerext.dll', 'coredpus.dll', 'coredpussvr.exe', 'coreglobconfig.dll', 'CoreMas.dll', 'CoreMessaging.dll', 'CoreMmRes.dll', 'CoreShell.dll', 'CoreShellAPI.dll', 'CoreShellExtFramework.dll', 'CoreUIComponents.dll', 'correngine.dll', 'CourtesyEngine.dll', 'CPFilters.dll', 'CredDialogBroker.dll', 'CredentialEnrollmentManager.exe', 'CredentialEnrollmentManagerForUser.dll', 'CredentialUIBroker.exe', 'CredProv2faHelper.dll', 'CredProvDataModel.dll', 'CredProvHelper.dll', 'credprovhost.dll', 'credprovs.dll', 'credprovslegacy.dll', 'credssp.dll', 'credui.dll', 'credwiz.exe', 'crypt32.dll', 'cryptbase.dll', 'cryptcatsvc.dll', 'cryptdlg.dll', 'cryptdll.dll', 'cryptext.dll', 'cryptnet.dll', 'cryptngc.dll', 'CryptoWinRT.dll', 'cryptsp.dll', 'cryptsvc.dll', 'crypttpmeksvc.dll', 'cryptui.dll', 'cryptuiwizard.dll', 'cryptxml.dll', 'cs-CZ', 'cscapi.dll', 'cscdll.dll', 'CscMig.dll', 'cscobj.dll', 'cscript.exe', 'cscsvc.dll', 'cscui.dll', 'csnp2uvc.dll', 'CspCellularSettings.dll', 'csplte.dll', 'CspProxy.dll', 'csrr.rs', 'csrsrv.dll', 'csrss.exe', 'CSystemEventsBrokerClient.dll', 'ctfmon.exe', 'cttune.exe', 'cttunesvr.exe', 'curl.exe', 'customers.xlsx', 'CustomInstallExec.exe', 'CustomModeApp.exe', 'CustomModeApp.exe.config', 'CustomModeAppv2_0.exe', 'CustomModeAppv2_0.exe.config', 'CustomShellHost.exe', 'cxcredprov.dll', 'CXHProvisioningServer.dll', 'C_037.NLS', 'C_10000.NLS', 'C_10001.NLS', 'C_10002.NLS', 'C_10003.NLS', 'C_10004.NLS', 'C_10005.NLS', 'C_10006.NLS', 'C_10007.NLS', 'C_10008.NLS', 'C_10010.NLS', 'C_10017.NLS', 'C_10021.NLS', 'C_10029.NLS', 'C_10079.NLS', 'C_10081.NLS', 'C_10082.NLS', 'C_1026.NLS', 'C_1047.NLS', 'C_1140.NLS', 'C_1141.NLS', 'C_1142.NLS', 'C_1143.NLS', 'C_1144.NLS', 'C_1145.NLS', 'C_1146.NLS', 'C_1147.NLS', 'C_1148.NLS', 'C_1149.NLS', 'C_1250.NLS', 'C_1251.NLS', 'C_1252.NLS', 'C_1253.NLS', 'C_1254.NLS', 'C_1255.NLS', 'C_1256.NLS', 'C_1257.NLS', 'C_1258.NLS', 'C_1361.NLS', 'C_20000.NLS', 'C_20001.NLS', 'C_20002.NLS', 'C_20003.NLS', 'C_20004.NLS', 'C_20005.NLS', 'C_20105.NLS', 'C_20106.NLS', 'C_20107.NLS', 'C_20108.NLS', 'C_20127.NLS', 'C_20261.NLS', 'C_20269.NLS', 'C_20273.NLS', 'C_20277.NLS', 'C_20278.NLS', 'C_20280.NLS', 'C_20284.NLS', 'C_20285.NLS', 'C_20290.NLS', 'C_20297.NLS', 'C_20420.NLS', 'C_20423.NLS', 'C_20424.NLS', 'C_20833.NLS', 'C_20838.NLS', 'C_20866.NLS', 'C_20871.NLS', 'C_20880.NLS', 'C_20905.NLS', 'C_20924.NLS', 'C_20932.NLS', 'C_20936.NLS', 'C_20949.NLS', 'C_21025.NLS', 'C_21027.NLS', 'C_21866.NLS', 'C_28591.NLS', 'C_28592.NLS', 'C_28593.NLS', 'C_28594.NLS', 'C_28595.NLS', 'C_28596.NLS', 'C_28597.NLS', 'C_28598.NLS', 'C_28599.NLS', 'c_28603.nls', 'C_28605.NLS', 'C_437.NLS', 'C_500.NLS', 'C_708.NLS', 'C_720.NLS', 'C_737.NLS', 'C_775.NLS', 'C_850.NLS', 'C_852.NLS', 'C_855.NLS', 'C_857.NLS', 'C_858.NLS', 'C_860.NLS', 'C_861.NLS', 'C_862.NLS', 'C_863.NLS', 'C_864.NLS', 'C_865.NLS', 'C_866.NLS', 'C_869.NLS', 'C_870.NLS', 'C_874.NLS', 'C_875.NLS', 'C_932.NLS', 'C_936.NLS', 'C_949.NLS', 'C_950.NLS', 'C_G18030.DLL', 'c_GSM7.DLL', 'C_IS2022.DLL', 'C_ISCII.DLL', 'd2d1.dll', 'd3d10.dll', 'd3d10core.dll', 'd3d10level9.dll', 'd3d10warp.dll', 'd3d10_1.dll', 'd3d10_1core.dll', 'd3d11.dll', 'd3d11on12.dll', 'D3D12.dll', 'D3D12Core.dll', 'd3d8thk.dll', 'd3d9.dll', 'd3d9on12.dll', 'D3DCompiler_47.dll', 'D3DSCache.dll', 'da-DK', 'dab.dll', 'dabapi.dll', 'DAConn.dll', 'dafAspInfraProvider.dll', 'dafBth.dll', 'DafDnsSd.dll', 'dafDockingProvider.dll', 'DAFESCL.dll', 'DafGip.dll', 'DAFIoT.dll', 'DAFIPP.dll', 'DAFMCP.dll', 'dafpos.dll', 'DafPrintProvider.dll', 'dafupnp.dll', 'dafWCN.dll', 'dafWfdProvider.dll', 'DAFWiProv.dll', 'DAFWSD.dll', 'DAMediaManager.dll', 'DAMM.dll', 'DaOtpCredentialProvider.dll', 'das.dll', 'dasHost.exe', 'dataclen.dll', 'DataExchange.dll', 'DataExchangeHost.exe', 'datamarketsvc.dll', 'DataStoreCacheDumpTool.exe', 'DataUsageHandlers.dll', 'DataUsageLiveTileTask.exe', 'datusage.dll', 'davclnt.dll', 'davhlpr.dll', 'DavSyncProvider.dll', 'daxexec.dll', 'dbgcore.dll', 'dbgeng.dll', 'dbghelp.dll', 'DbgModel.dll', 'dbnetlib.dll', 'dbnmpntw.dll', 'dccw.exe', 'dciman32.dll', 'dcntel.dll', 'dcomcnfg.exe', 'dcomp.dll', 'dcsvc.dll', 'DDACLSys.dll', 'DdcAntiTheftApi.dll', 'DdcClaimsApi.dll', 'DdcComImplementationsDesktop.dll', 'DDDS.dll', 'DDFs', 'ddisplay.dll', 'ddodiag.exe', 'DDOIProxy.dll', 'DDORes.dll', 'ddpchunk.dll', 'ddptrace.dll', 'ddputils.dll', 'ddp_ps.dll', 'ddraw.dll', 'ddrawex.dll', 'de-DE', 'debug.log', 'declaredconfiguration.dll', 'DefaultAccountTile.png', 'DefaultDeviceManager.dll', 'DefaultHrtfs.bin', 'DefaultPrinterProvider.dll', 'DefaultQuestions.json', 'Defrag.exe', 'defragproxy.dll', 'defragres.dll', 'defragsvc.dll', 'delegatorprovider.dll', 'DeliveryOptimizationMIProv.mof', 'DeliveryOptimizationMIProvUninstall.mof', 'deploymentcsphelper.exe', 'deploymentcsps.dll', 'desk.cpl', 'deskadp.dll', 'deskmon.dll', 'desktopimgdownldr.exe', 'DesktopKeepOnToastImg.gif', 'DesktopShellAppStateContract.dll', 'DesktopShellExt.dll', 'DesktopSpotlightToastIcon_Dark.png', 'DesktopSpotlightToastIcon_Light.png', 'DesktopSwitcherDataModel.dll', 'DesktopView.Internal.Broker.dll', 'DesktopView.Internal.Broker.ProxyStub.dll', 'DetailedReading-Default.xml', 'detoured.dll', 'DevDispItemProvider.dll', 'DeveloperOptionsSettingsHandlers.dll', 'devenum.dll', 'deviceaccess.dll', 'deviceassociation.dll', 'DeviceCensus.exe', 'DeviceCenter.dll', 'DeviceCredential.dll', 'DeviceCredentialDeployment.exe', 'DeviceDirectoryClient.dll', 'DeviceDisplayStatusManager.dll', 'DeviceDriverRetrievalClient.dll', 'DeviceEject.exe', 'DeviceElementSource.dll', 'DeviceEnroller.exe', 'DeviceFlows.DataModel.dll', 'DeviceMetadataRetrievalClient.dll', 'devicengccredprov.dll', 'DevicePairing.dll', 'DevicePairingExperienceMEM.dll', 'DevicePairingFolder.dll', 'DevicePairingProxy.dll', 'DevicePairingWizard.exe', 'DeviceProperties.exe', 'DeviceReactivation.dll', 'deviceregistration.dll', 'DeviceSetupManager.dll', 'DeviceSetupManagerAPI.dll', 'DeviceSetupStatusProvider.dll', 'DevicesFlowBroker.dll', 'DeviceSoftwareInstallationClient.dll', 'DeviceUpdateAgent.dll', 'DeviceUpdateCenterCsp.dll', 'DeviceUxRes.dll', 'devinv.dll', 'devmgmt.msc', 'devmgr.dll', 'DevModeRunAsUserConfig.msc', 'devobj.dll', 'DevPropMgr.dll', 'DevQueryBroker.dll', 'devrtl.dll', 'dfdts.dll', 'DFDWiz.exe', 'dfrgui.exe', 'dfscli.dll', 'dfshim.dll', 'DfsShlEx.dll', 'dggpext.dll', 'dhcpcmonitor.dll', 'dhcpcore.dll', 'dhcpcore6.dll', 'dhcpcsvc.dll', 'dhcpcsvc6.dll', 'dhcpsapi.dll', 'DHolographicDisplay.dll', 'DiagCpl.dll', 'diagnosticdataquery.dll', 'DiagnosticDataSettings.dll', 'DiagnosticInvoker.dll', 'DiagnosticLogCSP.dll', 'diagperf.dll', 'DiagSvc.dll', 'DiagSvcs', 'diagtrack.dll', 'dialclient.dll', 'dialer.exe', 'DialogBlockerProc.dll', 'DialogBlockingManager.dll', 'DialogBlockingService.dll', 'dialserver.dll', 'DictationManager.dll', 'difx64.exe', 'difxapi.dll', 'dimsjob.dll', 'dimsroam.dll', 'dinput.dll', 'dinput8.dll', 'Direct2DDesktop.dll', 'directmanipulation.dll', 'directml.dll', 'directxdatabaseupdater.exe', 'discan.dll', 'diskmgmt.msc', 'diskpart.exe', 'diskperf.exe', 'diskraid.exe', 'DiskSnapshot.conf', 'DiskSnapshot.exe', 'Dism', 'Dism.exe', 'DismApi.dll', 'DispBroker.Desktop.dll', 'DispBroker.dll', 'dispdiag.exe', 'dispex.dll', 'Display.dll', 'DisplayAudiox64.cab', 'DisplayManager.dll', 'DisplaySwitch.exe', 'DisplaySystemToastIcon.contrast-white.png', 'DisplaySystemToastIcon.png', 'djctq.rs', 'djoin.exe', 'dllhost.exe', 'dllhst3g.exe', 'dlnashext.dll', 'DMAlertListener.ProxyStub.dll', 'DmApiSetExtImplDesktop.dll', 'DMAppsRes.dll', 'dmcertinst.exe', 'dmcfghost.exe', 'dmcfgutils.dll', 'dmclient.exe', 'dmcmnutils.dll', 'dmcommandlineutils.dll', 'dmcsps.dll', 'dmdlgs.dll', 'dmdskmgr.dll', 'dmdskres.dll', 'dmdskres2.dll', 'dmenrollengine.dll'

In [11]:
df = pd.read_excel('sales1.xlsx', sheet_name='Customer')
df.head()

  Customer ID    Customer Name    Segment
0    CG-12520      Claire Gute   Consumer
1    CG-12520      Claire Gute   Consumer
2    DV-13045  Darrin Van Huff  Corporate
3    SO-20335   Sean O'Donnell   Consumer
4    SO-20335   Sean O'Donnell   Consumer

In [17]:
df=pd.read_excel('sales1.xlsx', sheet_name='Orders')
df.head()

,Order Date,Ship Date,Ship Mode,Customer ID,Country,City,State,Postal Code,Region
0,08/11/2017,11/11/2017,Second Class,CG-12520,United States,Henderson,Kentucky,42420.0,South
1,08/11/2017,11/11/2017,Second Class,CG-12520,United States,Henderson,Kentucky,42420.0,South
2,12/06/2017,16/06/2017,Second Class,DV-13045,United States,Los Angeles,California,90036.0,West
3,11/10/2016,18/10/2016,Standard Class,SO-20335,United States,Fort Lauderdale,Florida,33311.0,South
4,11/10/2016,18/10/2016,Standard Class,SO-20335,United States,Fort Lauderdale,Florida,33311.0,South

In [1]:
import os
os.getcwd()

'C:\\Windows\\system32'

In [1]:
import pandas as pd
file_path = 'sales3.xlsx' 
data_df = pd.read_excel(file_path, sheet_name='Data')
print(data_df.head())

   Row ID        Order ID  Order Date   Ship Date       Ship Mode Customer ID  \
0       1  CA-2017-152156  08/11/2017  11/11/2017    Second Class    CG-12520
1       2  CA-2017-152156  08/11/2017  11/11/2017    Second Class    CG-12520
2       3  CA-2017-138688  12/06/2017  16/06/2017    Second Class    DV-13045
3       4  US-2016-108966  11/10/2016  18/10/2016  Standard Class    SO-20335
4       5  US-2016-108966  11/10/2016  18/10/2016  Standard Class    SO-20335

     Customer Name    Segment        Country             City       State  \
0      Claire Gute   Consumer  United States        Henderson    Kentucky
1      Claire Gute   Consumer  United States        Henderson    Kentucky
2  Darrin Van Huff  Corporate  United States      Los Angeles  California
3   Sean O'Donnell   Consumer  United States  Fort Lauderdale     Florida
4   Sean O'Donnell   Consumer  United States  Fort Lauderdale     Florida

   Postal Code Region       Product ID         Category Sub-Category  \
0      42420.0  South  FUR-BO-10001798        Furniture    Bookcases
1      42420.0  South  FUR-CH-10000454        Furniture       Chairs
2      90036.0   West  OFF-LA-10000240  Office Supplies       Labels
3      33311.0  South  FUR-TA-10000577        Furniture       Tables
4      33311.0  South  OFF-ST-10000760  Office Supplies      Storage

                                        Product Name     Sales
0                  Bush Somerset Collection Bookcase  261.9600
1  Hon Deluxe Fabric Upholstered Stacking Chairs,...  731.9400
2  Self-Adhesive Address Labels for Typewriters b...   14.6200
3      Bretford CR4500 Series Slim Rectangular Table  957.5775
4                     Eldon Fold 'N Roll Cart System   22.3680

In [27]:
df = pd.read_excel(file_path, sheet_name="Customer")
print(df.head())

  Customer ID    Customer Name   Segment
0    CG-12520      Claire Gute  Consumer
1    SO-20335   Sean O'Donnell  Consumer
2    BH-11710  Brosina Hoffman  Consumer
3    AA-10480     Andrew Allen  Consumer
4    IM-15070     Irene Maddox  Consumer

In [28]:
df = pd.read_excel(file_path, sheet_name="Products")
print(df.head())

        Product ID         Category Sub-Category  \
0  OFF-PA-10002365  Office Supplies        Paper
1  OFF-PA-10000249  Office Supplies        Paper
2  OFF-PA-10001569  Office Supplies        Paper
3  OFF-PA-10000587  Office Supplies        Paper
4  OFF-PA-10003892  Office Supplies        Paper

                             Product Name
0                              Xerox 1967
1                       Easy-Staple Paper
2                               Xerox 232
3  Array Parchment Paper, Assorted Colors
4                              Xerox 1943

In [29]:
df = pd.read_excel(file_path, sheet_name="Order")
print(df.head())

         Order ID Order Date  Ship Date       Ship Mode Customer ID  \
0  CA-2017-121755 2017-01-16 2017-01-20    Second Class    EH-13945
1  CA-2017-101343 2017-07-17 2017-07-22  Standard Class    RA-19885
2  CA-2018-163405 2018-12-21 2018-12-25  Standard Class    BN-11515
3  CA-2015-159338 2015-06-25 2015-06-28     First Class    NS-18640
4  CA-2015-121664 2015-05-06 2015-05-10  Standard Class    HP-14815

         Country         City       State  Postal Code Region  \
0  United States  Los Angeles  California        90049   West
1  United States  Los Angeles  California        90049   West
2  United States  Los Angeles  California        90049   West
3  United States  Los Angeles  California        90049   West
4  United States  Los Angeles  California        90049   West

   Order Date (Year) Order Date (Quarter)  Order Date (Month Index)  \
0               2017                 Qtr1                         1
1               2017                 Qtr3                         7
2               2018                 Qtr4                        12
3               2015                 Qtr2                         6
4               2015                 Qtr2                         5

  Order Date (Month)  shipping time
0                Jan              4
1                Jul              5
2                Dec              4
3                Jun              3
4                May              4

In [30]:
df = pd.read_excel(file_path, sheet_name="Sales Details")
print(df.head())

Empty DataFrame
Columns: [Sales Details ]
Index: []

In [31]:
df = pd.read_excel(file_path, sheet_name="Sales Details")
print(df.head())

Empty DataFrame
Columns: [Sales Details ]
Index: []

In [33]:
df = pd.read_excel(file_path, sheet_name="Sales Detalis")
print(df.head())

         Order ID       Product ID      Sales  Column1  Column2  Column3  \
0  CA-2017-152156  FUR-BO-10001798   261.9600      NaN      NaN      NaN
1  CA-2017-152156  FUR-CH-10000454   731.9400      NaN      NaN      NaN
2  CA-2017-114489  FUR-CH-10000454  1951.8400      NaN      NaN      NaN
3  CA-2017-138688  OFF-LA-10000240    14.6200      NaN      NaN      NaN
4  US-2016-108966  FUR-TA-10000577   957.5775      NaN      NaN      NaN

   Column4
0      NaN
1      NaN
2      NaN
3      NaN
4      NaN

In [34]:
df.shape

(9792, 7)

In [35]:
df.columns

Index(['Order ID', 'Product ID', 'Sales', 'Column1', 'Column2', 'Column3',
       'Column4'],
      dtype='object')

In [36]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9792 entries, 0 to 9791
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Order ID    9792 non-null   object
 1   Product ID  9792 non-null   object
 2   Sales       9792 non-null   float64
 3   Column1     0 non-null      float64
 4   Column2     0 non-null      float64
 5   Column3     0 non-null      float64
 6   Column4     0 non-null      float64
dtypes: float64(5), object(2)
memory usage: 535.6+ KB

In [37]:
df.head()

,Order ID,Product ID,Sales,Column1,Column2,Column3,Column4
0,CA-2017-152156,FUR-BO-10001798,261.9600,NaN,NaN,NaN,NaN
1,CA-2017-152156,FUR-CH-10000454,731.9400,NaN,NaN,NaN,NaN
2,CA-2017-114489,FUR-CH-10000454,1951.8400,NaN,NaN,NaN,NaN
3,CA-2017-138688,OFF-LA-10000240,14.6200,NaN,NaN,NaN,NaN
4,US-2016-108966,FUR-TA-10000577,957.5775,NaN,NaN,NaN,NaN

In [38]:
df.describe()

              Sales  Column1  Column2  Column3  Column4
count   9792.000000      0.0      0.0      0.0      0.0
mean     230.928861      NaN      NaN      NaN      NaN
std      627.074062      NaN      NaN      NaN      NaN
min        0.444000      NaN      NaN      NaN      NaN
25%       17.235000      NaN      NaN      NaN      NaN
50%       54.432000      NaN      NaN      NaN      NaN
75%      210.568000      NaN      NaN      NaN      NaN
max    22638.480000      NaN      NaN      NaN      NaN

In [39]:
df.isnull()

      Order ID  Product ID  Sales  Column1  Column2  Column3  Column4
0        False       False  False     True     True     True     True
1        False       False  False     True     True     True     True
2        False       False  False     True     True     True     True
3        False       False  False     True     True     True     True
4        False       False  False     True     True     True     True
...        ...         ...    ...      ...      ...      ...      ...
9787     False       False  False     True     True     True     True
9788     False       False  False     True     True     True     True
9789     False       False  False     True     True     True     True
9790     False       False  False     True     True     True     True
9791     False       False  False     True     True     True     True

[9792 rows x 7 columns]

In [45]:
import pandas as pd
file_path = r"D:\رواد مصر 2025\practice , assignments\technical assignment\Final project\اخر تعديل 15-10\final normalization\نهائي\sales3.xlsx"
orders_df = pd.read_excel(file_path, sheet_name="Order")
missing_values = orders_df.isnull()
print(missing_values)

      Order ID  Order Date  Ship Date  Ship Mode  Customer ID  Country   City  \
0        False       False      False      False        False    False  False
1        False       False      False      False        False    False  False
2        False       False      False      False        False    False  False
3        False       False      False      False        False    False  False
4        False       False      False      False        False    False  False
...        ...         ...        ...        ...          ...      ...    ...
4917     False       False      False      False        False    False  False
4918     False       False      False      False        False    False  False
4919     False       False      False      False        False    False  False
4920     False       False      False      False        False    False  False
4921     False       False      False      False        False    False  False

      State  Postal Code  Region  Order Date (Year)  Order Date (Quarter)  \
0     False        False   False              False                 False
1     False        False   False              False                 False
2     False        False   False              False                 False
3     False        False   False              False                 False
4     False        False   False              False                 False
...     ...          ...     ...                ...                   ...
4917  False        False   False              False                 False
4918  False        False   False              False                 False
4919  False        False   False              False                 False
4920  False        False   False              False                 False
4921  False        False   False              False                 False

      Order Date (Month Index)  Order Date (Month)  shipping time
0                        False               False          False
1                        False               False          False
2                        False               False          False
3                        False               False          False
4                        False               False          False
...                        ...                 ...            ...
4917                     False               False          False
4918                     False               False          False
4919                     False               False          False
4920                     False               False          False
4921                     False               False          False

[4922 rows x 15 columns]

In [46]:
import pandas as pd
file_path = r"D:\رواد مصر 2025\practice , assignments\technical assignment\Final project\اخر تعديل 15-10\final normalization\نهائي\sales3.xlsx"
orders_df = pd.read_excel(file_path, sheet_name="Products")
missing_values = orders_df.isnull()
print(missing_values)

      Product ID  Category  Sub-Category  Product Name
0          False     False         False         False
1          False     False         False         False
2          False     False         False         False
3          False     False         False         False
4          False     False         False         False
...          ...       ...           ...           ...
1811       False     False         False         False
1812       False     False         False         False
1813       False     False         False         False
1814       False     False         False         False
1815       False     False         False         False

[1816 rows x 4 columns]

In [47]:
import pandas as pd
file_path = r"D:\رواد مصر 2025\practice , assignments\technical assignment\Final project\اخر تعديل 15-10\final normalization\نهائي\sales3.xlsx"
orders_df = pd.read_excel(file_path, sheet_name="Sales Detalis")
missing_values = orders_df.isnull()
print(missing_values)

      Order ID  Product ID  Sales  Column1  Column2  Column3  Column4
0        False       False  False     True     True     True     True
1        False       False  False     True     True     True     True
2        False       False  False     True     True     True     True
3        False       False  False     True     True     True     True
4        False       False  False     True     True     True     True
...        ...         ...    ...      ...      ...      ...      ...
9787     False       False  False     True     True     True     True
9788     False       False  False     True     True     True     True
9789     False       False  False     True     True     True     True
9790     False       False  False     True     True     True     True
9791     False       False  False     True     True     True     True

[9792 rows x 7 columns]

In [48]:
import pandas as pd
file_path = r"D:\رواد مصر 2025\practice , assignments\technical assignment\Final project\اخر تعديل 15-10\final normalization\نهائي\sales3.xlsx"
orders_df = pd.read_excel(file_path, sheet_name="Customer")
missing_values = orders_df.isnull()
print(missing_values)

     Customer ID  Customer Name  Segment
0          False          False    False
1          False          False    False
2          False          False    False
3          False          False    False
4          False          False    False
..           ...            ...      ...
788        False          False    False
789        False          False    False
790        False          False    False
791        False          False    False
792        False          False    False

[793 rows x 3 columns]

In [49]:
missing_values_count = orders_df.isnull().sum()
print(missing_values_count)

Customer ID      0
Customer Name    0
Segment          0
dtype: int64

In [50]:
df.isnull().sum()

Order ID         0
Product ID       0
Sales            0
Column1       9792
Column2       9792
Column3       9792
Column4       9792
dtype: int64

In [54]:
df.duplicated()

0       False
1       False
2       False
3       False
4       False
        ...
9787    False
9788    False
9789    False
9790    False
9791    False
Length: 9792, dtype: bool

In [55]:
df. duplicated().sum

<bound method Series.sum of 0       False
1       False
2       False
3       False
4       False
        ...
9787    False
9788    False
9789    False
9790    False
9791    False
Length: 9792, dtype: bool>

In [56]:
df[df.duplicated()]

Empty DataFrame
Columns: [Order ID, Product ID, Sales, Column1, Column2, Column3, Column4]
Index: []

In [57]:
df.describe()

              Sales  Column1  Column2  Column3  Column4
count   9792.000000      0.0      0.0      0.0      0.0
mean     230.928861      NaN      NaN      NaN      NaN
std      627.074062      NaN      NaN      NaN      NaN
min        0.444000      NaN      NaN      NaN      NaN
25%       17.235000      NaN      NaN      NaN      NaN
50%       54.432000      NaN      NaN      NaN      NaN
75%      210.568000      NaN      NaN      NaN      NaN
max    22638.480000      NaN      NaN      NaN      NaN

In [62]:
print(df.columns)

Index(['Order ID', 'Product ID', 'Sales', 'Column1', 'Column2', 'Column3',
       'Column4'],
      dtype='object')

In [63]:
df['Order ID'].value_counts().head(32)

Order ID
CA-2018-100111    14
CA-2018-157987    12
US-2017-108504    11
CA-2017-165330    11
CA-2016-131338    10
CA-2017-105732    10
US-2016-126977    10
CA-2015-106439     9
CA-2016-104346     9
CA-2016-164882     9
CA-2016-158421     9
CA-2017-145177     9
CA-2018-140949     9
CA-2016-132626     9
CA-2018-117457     9
US-2017-114013     9
US-2016-163433     9
CA-2018-102925     8
CA-2018-140872     8
CA-2018-161956     8
CA-2015-167927     8
CA-2017-152730     8
CA-2016-121720     8
CA-2018-164756     8
US-2018-118087     8
CA-2018-156776     8
CA-2016-167010     8
US-2017-110156     8
CA-2018-110905     8
CA-2015-129364     8
CA-2015-142769     8
CA-2018-128363     7
Name: count, dtype: int64

In [ ]:
ANALYSIS

In [67]:
df.columns = df.columns.str.strip()
print(df.columns)

Index(['Order ID', 'Product ID', 'Sales', 'Column1', 'Column2', 'Column3',
       'Column4'],
      dtype='object')

In [69]:
file_path = r"D:\رواد مصر 2025\practice , assignments\technical assignment\Final project\اخر تعديل 15-10\final normalization\نهائي\sales3.xlsx"
customer_df = pd.read_excel(file_path, sheet_name="Customer")
print(customer_df.columns)

Index(['Customer ID', 'Customer Name', 'Segment'], dtype='object')

In [72]:

customer_df.columns = customer_df.columns.str.strip()
print(customer_df.columns)
total_customers = customer_df['Customer ID'].nunique()
print(f"إجمالي عدد العملاء: {total_customers}")

Index(['Customer ID', 'Customer Name', 'Segment'], dtype='object')
إجمالي عدد العملاء: 793

In [75]:
import pandas as pd
file_path = r"D:\رواد مصر 2025\practice , assignments\technical assignment\Final project\اخر تعديل 15-10\final normalization\نهائي\sales3.xlsx"
order_df = pd.read_excel(file_path, sheet_name="Order")
order_df.columns = order_df.columns.str.strip()
order_df['Order Date'] = pd.to_datetime(order_df['Order Date'], errors='coerce')
order_df['Year'] = order_df['Order Date'].dt.year
customers_per_year = order_df.groupby('Year')['Customer ID'].nunique()
print(customers_per_year)

Year
2015    589
2016    567
2017    635
2018    690
Name: Customer ID, dtype: int64

In [82]:
print(order_df.columns)

Index(['Order ID', 'Order Date', 'Ship Date', 'Ship Mode', 'Customer ID',
       'Country', 'City', 'State', 'Postal Code', 'Region',
       'Order Date (Year)', 'Order Date (Quarter)', 'Order Date (Month Index)',
       'Order Date (Month)', 'shipping time'],
      dtype='object')

In [85]:
import pandas as pd
file_path = r"D:\رواد مصر 2025\practice , assignments\technical assignment\Final project\اخر تعديل 15-10\final normalization\نهائي\sales3.xlsx"
customer_df = pd.read_excel(file_path, sheet_name="Customer")
customer_df.columns = customer_df.columns.str.strip()
customers_per_segment = customer_df.groupby('Segment')['Customer ID'].nunique()
customers_percentage = (customers_per_segment / customers_per_segment.sum()) * 100
print(customers_percentage)

Segment
Consumer       51.576293
Corporate      29.760404
Home Office    18.663304
Name: Customer ID, dtype: float64

In [89]:
import pandas as pd
file_path = r"D:\رواد مصر 2025\practice , assignments\technical assignment\Final project\اخر تعديل 15-10\final normalization\نهائي\sales3.xlsx"
order_df = pd.read_excel(file_path, sheet_name="Order")
order_df.columns = order_df.columns.str.strip()
orders_per_customer = order_df.groupby('Customer ID')['Order ID'].nunique()
top_10_customers_orders = orders_per_customer.sort_values(ascending=False).head(10)
print(top_10_customers_orders)

Customer ID
EP-13915    17
CK-12205    13
ZC-21910    13
JE-15745    13
PG-18820    13
HG-14965    12
CL-12565    12
DK-12835    12
SJ-20125    12
NS-18640    12
Name: Order ID, dtype: int64

In [102]:
print(sales_details_df.columns)

Index(['Sales Details'], dtype='object')

In [ ]:
import pandas as pd
file_path = r"D:\رواد مصر 2025\practice , assignments\technical assignment\Final project\اخر تعديل 15-10\final normalization\نهائي\sales3.xlsx"
sales_details_df = pd.read_excel(file_path, sheet_name="Sales Details")
products_df = pd.read_excel(file_path, sheet_name="Products")
sales_details_df.columns = sales_details_df.columns.str.strip()
products_df.columns = products_df.columns.str.strip()
merged_df = pd.merge(sales_details_df, products_df, on="Product ID", how="inner")
total_sales_per_product = merged_df.groupby('Product Name')['Sales'].sum()
top_5_products = total_sales_per_product.sort_values(ascending=False).head(5)
print(top_5_products)

In [126]:
import pandas as pd
file_path = r"D:\رواد مصر 2025\practice , assignments\technical assignment\Final project\اخر تعديل 15-10\final normalization\نهائي\sales3.xlsx"
products_df = pd.read_excel(file_path, sheet_name="Products")
products_df.columns = products_df.columns.str.strip()
total_categories = products_df['Category'].nunique()
print(f"عدد الفئات: {total_categories}")

عدد الفئات: 3

In [127]:
import pandas as pd
file_path = r"D:\رواد مصر 2025\practice , assignments\technical assignment\Final project\اخر تعديل 15-10\final normalization\نهائي\sales3.xlsx"
products_df = pd.read_excel(file_path, sheet_name="Products")
products_df.columns = products_df.columns.str.strip()
total_subcategories = products_df['Sub-Category'].nunique()
print(f"عدد الـ Sub-Category: {total_subcategories}")

عدد الـ Sub-Category: 17

In [128]:
import pandas as pd
file_path = r"D:\رواد مصر 2025\practice , assignments\technical assignment\Final project\اخر تعديل 15-10\final normalization\نهائي\sales3.xlsx"
products_df = pd.read_excel(file_path, sheet_name="Products")
products_df.columns = products_df.columns.str.strip()
total_products = products_df['Product ID'].nunique()
print(f"عدد المنتجات: {total_products}")

عدد المنتجات: 1816

In [135]:
import pandas as pd
file_path = r"D:\رواد مصر 2025\practice , assignments\technical assignment\Final project\اخر تعديل 15-10\final normalization\نهائي\sales3.xlsx"
sales_details_df = pd.read_excel(file_path, sheet_name="Sales Detalis")
products_df = pd.read_excel(file_path, sheet_name="Products")
sales_details_df.columns = sales_details_df.columns.str.strip()
products_df.columns = products_df.columns.str.strip()
merged_df = pd.merge(sales_details_df, products_df, on="Product ID", how="inner")
total_sales_per_product = merged_df.groupby('Product Name')['Sales'].sum()
bottom_5_products = total_sales_per_product.sort_values(ascending=True).head(5)
print(bottom_5_products)

Product Name
Eureka Disposable Bags For Sanitaire Vibra Groomer I Upright Vac    1.624
Avery 5                                                             5.760
Xerox 20                                                            6.480
Grip Seal Envelopes                                                 7.072
Acme Serrated Blade Letter Opener                                   7.632
Name: Sales, dtype: float64

In [136]:
import pandas as pd
file_path = r"D:\رواد مصر 2025\practice , assignments\technical assignment\Final project\اخر تعديل 15-10\final normalization\نهائي\sales3.xlsx"
sales_details_df = pd.read_excel(file_path, sheet_name="Sales Detalis")
products_df = pd.read_excel(file_path, sheet_name="Products")
sales_details_df.columns = sales_details_df.columns.str.strip()
products_df.columns = products_df.columns.str.strip()
merged_df = pd.merge(sales_details_df, products_df, on="Product ID", how="inner")
total_sales_per_product = merged_df.groupby('Product Name')['Sales'].sum()
top_5_products = total_sales_per_product.sort_values(ascending=False).head(5)
print(top_5_products)

Product Name
Canon Imageclass 2200 Advanced Copier                                          61599.824
Fellowes Pb500 Electric Punch Plastic Comb Binding Machine With Manual Bind    27453.384
Cisco Telepresence System Ex90 Videoconferencing Unit                          22638.480
Hon 5400 Series Task Chairs For Big And Tall                                   21870.576
Gbc Docubind Tl300 Electric Binding System                                     19823.479
Name: Sales, dtype: float64

In [147]:
import pandas as pd
file_path = r"D:\رواد مصر 2025\practice , assignments\technical assignment\Final project\اخر تعديل 15-10\final normalization\نهائي\sales3.xlsx"
orders_df = pd.read_excel(file_path, sheet_name="Order")
orders_df.columns = orders_df.columns.str.strip()
print("Order DataFrame Columns:", orders_df.columns)
print("Does 'Ship Mode' exist?", 'Ship Mode' in orders_df.columns)
print("Does 'Shipping Time' exist?", 'Shipping Time' in orders_df.columns)
if 'Ship Mode' in orders_df.columns and 'Shipping Time' in orders_df.columns:
    avg_shipping_time_by_mode = orders_df.groupby('Ship Mode')['Shipping Time'].mean()
    print(avg_shipping_time_by_mode)
else:
    print("العمود 'Ship Mode' أو 'Shipping Time' غير موجود في البيانات.")

Order DataFrame Columns: Index(['Order ID', 'Order Date', 'Ship Date', 'Ship Mode', 'Customer ID',
       'Country', 'City', 'State', 'Postal Code', 'Region',
       'Order Date (Year)', 'Order Date (Quarter)', 'Order Date (Month Index)',
       'Order Date (Month)', 'shipping time'],
      dtype='object')
Does 'Ship Mode' exist? True
Does 'Shipping Time' exist? False
العمود 'Ship Mode' أو 'Shipping Time' غير موجود في البيانات.

In [150]:
import pandas as p
file_path = r"D:\رواد مصر 2025\practice , assignments\technical assignment\Final project\اخر تعديل 15-10\final normalization\نهائي\sales3.xlsx"
orders_df = pd.read_excel(file_path, sheet_name="Order")
orders_df.columns = orders_df.columns.str.strip()
orders_df['Order Date'] = pd.to_datetime(orders_df['Order Date'])
orders_df['Ship Date'] = pd.to_datetime(orders_df['Ship Date'])
orders_df['Shipping Days Delay'] = (orders_df['Ship Date'] - orders_df['Order Date']).dt.days
avg_shipping_delay_per_region = orders_df.groupby('Region')['Shipping Days Delay'].mean()
print(avg_shipping_delay_per_region)

Region
Central    4.012111
East       3.937911
South      3.976543
West       3.928166
Name: Shipping Days Delay, dtype: float64

In [156]:
import pandas as pd
file_path = r"D:\رواد مصر 2025\practice , assignments\technical assignment\Final project\اخر تعديل 15-10\final normalization\نهائي\sales3.xlsx"
orders_df = pd.read_excel(file_path, sheet_name="Order")
orders_df.columns = orders_df.columns.str.strip()
orders_df['Order Date'] = pd.to_datetime(orders_df['Order Date'])
orders_df['Ship Date'] = pd.to_datetime(orders_df['Ship Date'])
orders_df['Shipping Time'] = (orders_df['Ship Date'] - orders_df['Order Date']).dt.days
avg_shipping_time = orders_df['Shipping Time'].mean()
print(f"متوسط وقت الشحن: {avg_shipping_time} أيام")

متوسط وقت الشحن: 3.958553433563592 أيام

In [163]:
import pandas as pd
file_path = r"D:\رواد مصر 2025\practice , assignments\technical assignment\Final project\اخر تعديل 15-10\final normalization\نهائي\sales3.xlsx"
sales_details_df = pd.read_excel(file_path, sheet_name="Sales Detalis")
sales_details_df.columns = sales_details_df.columns.str.strip()
print(sales_details_df.columns)
total_sales = sales_details_df['Sales'].sum()
print(f"مجموع المبيعات: {total_sales}")

Index(['Order ID', 'Product ID', 'Sales', 'Column1', 'Column2', 'Column3',
       'Column4'],
      dtype='object')
مجموع المبيعات: 2261255.4107

In [166]:
import pandas as pd
file_path = r"D:\رواد مصر 2025\practice , assignments\technical assignment\Final project\اخر تعديل 15-10\final normalization\نهائي\sales3.xlsx"
sales_details_df = pd.read_excel(file_path, sheet_name="Sales Detalis")
orders_df = pd.read_excel(file_path, sheet_name="Order")
saes_details_df.columns = sales_details_df.columns.str.strip()
orders_df.columns = orders_df.columns.str.strip()
merged_df = pd.merge(sales_details_df, orders_df, on="Order ID", how="inner")
print(merged_df.columns)
sales_per_region = merged_df.groupby('Region')['Sales'].sum()
print(sales_per_region)

Index(['Order ID', 'Product ID', 'Sales', 'Column1', 'Column2', 'Column3',
       'Column4', 'Order Date', 'Ship Date', 'Ship Mode', 'Customer ID',
       'Country', 'City', 'State', 'Postal Code', 'Region',
       'Order Date (Year)', 'Order Date (Quarter)', 'Order Date (Month Index)',
       'Order Date (Month)', 'shipping time'],
      dtype='object')
Region
Central    492646.9132
East       669237.3540
South      389151.4590
West       710219.6845
Name: Sales, dtype: float64

In [179]:
import pandas as pd
file_path = r"D:\رواد مصر 2025\practice , assignments\technical assignment\Final project\اخر تعديل 15-10\final normalization\نهائي\sales3.xlsx"
sales_details_df = pd.read_excel(file_path, sheet_name="Sales Detalis")
orders_df = pd.read_excel(file_path, sheet_name="Order")
sales_details_df.columns = sales_details_df.columns.str.strip()
orders_df.columns = orders_df.columns.str.strip()
merged_df = pd.merge(sales_details_df, orders_df, on="Order ID", how="inner")
sales_per_state = merged_df.groupby('State')['Sales'].sum()
top_3_states = sales_per_state.sort_values(ascending=False).head(3)
print("Top 3 States by Sales:")
print(top_3_states)
less_3_states = sales_per_state.sort_values(ascending=True).head(3)
print("Less 3 States by Sales:")
print(less_3_states)

Top 3 States by Sales:
State
California    446306.4635
New York      306361.1470
Texas         168572.5322
Name: Sales, dtype: float64
Less 3 States by Sales:
State
North Dakota      919.910
West Virginia    1209.824
Maine            1270.530
Name: Sales, dtype: float64